TableReservations/Controllers/AdminController.cs
using TableReservations.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TableReservations.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }


        // Index
        public IActionResult Index()
        {
            return View();
        }
        

        // Add other actions as needed
    }
}

TableReservations/Controllers/OrderController.cs
using TableReservations.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Globalization;

namespace TableReservations.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await _context.Orders.Include(o => o.OrderDetails).ToListAsync();

            var orderViewModels = orders.Select(o => new OrderViewModel
            {
                Order = o,
                TotalPrice = o.OrderDetails.Sum(od => od.Quantity * od.Price)
            }).ToList();

            return View(orderViewModels);
        }
        
        public async Task<IActionResult> Revenue()
        {
            var orders = await _context.Orders.Include(o => o.OrderDetails).ToListAsync();

            var weeklyRevenue = orders
                .GroupBy(o => CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(o.OrderDate, CalendarWeekRule.FirstDay, DayOfWeek.Monday))
                .Select(g => new RevenueData { Period = $"Week {g.Key}", Revenue = g.Sum(o => o.OrderDetails.Sum(od => od.Quantity * od.Price)) })
                .ToList();

            var monthlyRevenue = orders
                .GroupBy(o => o.OrderDate.Month)
                .Select(g => new RevenueData { Period = $"Month {g.Key}", Revenue = g.Sum(o => o.OrderDetails.Sum(od => od.Quantity * od.Price)) })
                .ToList();

            var yearlyRevenue = orders
                .GroupBy(o => o.OrderDate.Year)
                .Select(g => new RevenueData { Period = $"Year {g.Key}", Revenue = g.Sum(o => o.OrderDetails.Sum(od => od.Quantity * od.Price)) })
                .ToList();

            var totalRevenue = orders.Sum(o => o.OrderDetails.Sum(od => od.Quantity * od.Price));

            var revenue = new Revenue
            {
                WeeklyRevenue = weeklyRevenue,
                MonthlyRevenue = monthlyRevenue,
                YearlyRevenue = yearlyRevenue,
                TotalRevenue = totalRevenue
            };

            return View(revenue);
        }

        

        // Thêm các action khác như Create, Edit, Delete...
    }
}

TableReservations/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;

namespace TableReservations.Controllers;

public class SharedController : Controller
{
    public IActionResult About()
    {
        throw new NotImplementedException();
    }
}

TableReservations/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper"/>
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Admin" asp-action="Index">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">ADMIN
        </div>
    </a>



    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a asp-action="Index" asp-controller="Order" class="nav-link">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Quản Lý Đơn Hàng</span>
        </a>
    </li>



    @* <!-- Heading --> *@
    @* <div class="sidebar-heading"> *@
    @*     Interface *@
    @* </div> *@

    <!-- Nav Item - Pages Collapse Menu -->
    @* <li class="nav-item"> *@
    @*     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" *@
    @*        aria-expanded="true" aria-controls="collapseTwo"> *@
    @*         <i class="fas fa-fw fa-cog"></i> *@
    @*         <span>Components</span> *@
    @*     </a> *@
    @*     <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar"> *@
    @*         <div class="bg-white py-2 collapse-inner rounded"> *@
    @*             <h6 class="collapse-header">Custom Components:</h6> *@
    @*             <a class="collapse-item" href="buttons.html">Buttons</a> *@
    @*             <a class="collapse-item" href="cards.html">Cards</a> *@
    @*         </div> *@
    @*     </div> *@
    @* </li> *@
    @* *@
    @* <!-- Nav Item - Utilities Collapse Menu --> *@
    @* <li class="nav-item"> *@
    @*     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" *@
    @*        aria-expanded="true" aria-controls="collapseUtilities"> *@
    @*         <i class="fas fa-fw fa-wrench"></i> *@
    @*         <span>Utilities</span> *@
    @*     </a> *@
    @*     <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" *@
    @*          data-parent="#accordionSidebar"> *@
    @*         <div class="bg-white py-2 collapse-inner rounded"> *@
    @*             <h6 class="collapse-header">Custom Utilities:</h6> *@
    @*             <a class="collapse-item" href="utilities-color.html">Colors</a> *@
    @*             <a class="collapse-item" href="utilities-border.html">Borders</a> *@
    @*             <a class="collapse-item" href="utilities-animation.html">Animations</a> *@
    @*             <a class="collapse-item" href="utilities-other.html">Other</a> *@
    @*         </div> *@
    @*     </div> *@
    @* </li> *@
    @* *@
    @* <!-- Divider --> *@
    @* <hr class="sidebar-divider"> *@
    @* *@
    @* <!-- Heading --> *@
    @* <div class="sidebar-heading"> *@
    @*     Addons *@
    @* </div> *@
    @* *@
    @* <!-- Nav Item - Pages Collapse Menu --> *@
    @* <li class="nav-item"> *@
    @*     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" *@
    @*        aria-expanded="true" aria-controls="collapsePages"> *@
    @*         <i class="fas fa-fw fa-folder"></i> *@
    @*         <span>Pages</span> *@
    @*     </a> *@
    @*     <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar"> *@
    @*         <div class="bg-white py-2 collapse-inner rounded"> *@
    @*             <h6 class="collapse-header">Login Screens:</h6> *@
    @*             <a class="collapse-item" href="login.html">Login</a> *@
    @*             <a class="collapse-item" href="register.html">Register</a> *@
    @*             <a class="collapse-item" href="forgot-password.html">Forgot Password</a> *@
    @*             <div class="collapse-divider"></div> *@
    @*             <h6 class="collapse-header">Other Pages:</h6> *@
    @*             <a class="collapse-item" href="404.html">404 Page</a> *@
    @*             <a class="collapse-item" href="blank.html">Blank Page</a> *@
    @*         </div> *@
    @*     </div> *@
    @* </li> *@

    <!-- Nav Item - Menu -->
    <li class="nav-item">
        <a asp-action="Index" asp-controller="Product" class="nav-link">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Quản Lý Menu</span>
        </a>
    </li>
    <li class="nav-item">
            <a asp-action="Revenue" asp-controller="Order" class="nav-link">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Tổng doanh thu</span>
            </a>
        </li>
    
    <!-- Nav Item - Product Management -->

    <!-- Nav Item - Tables -->
    <li class="nav-item">
            <a asp-action="Index" asp-controller="TableLocations" class="nav-link">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Table</span>
            </a>
        </li>
    


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Quay lại trang chủ</a>
</ul>
<!-- End of Sidebar -->
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column"/>
<!-- Main Content -->
<div id="content">

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
    
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search"
                               aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>


        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                <img class="img-profile rounded-circle"
                     src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        @* <h1 class="h3 mb-0 text-gray-800">Dashboard</h1> *@
        @* <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i *@
        @*         class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> *@
    </div>
     @RenderBody()
    @RenderSection("Scripts", required: false)
    <!-- End of Footer -->
</div>

<!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>
<!-- Bootstrap core JavaScript-->
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/lib/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/js/sb-admin-2.min.js"></script>
<!-- Page level plugins -->
<script src="~/lib/chart.js/Chart.min.js"></script>
<!-- Page level custom scripts -->
<script src="~/js/demo/chart-area-demo.js"></script>
<script src="~/js/demo/chart-pie-demo.js"></script>

</body>

</html>

TableReservations/Views/Shared/_Layout.cshtml
<DOCTYPE html />
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] RESTORAN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>

    @* HEADER *@
    <div class="container-xxl position-relative p-0">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
            <a href="" class="navbar-brand p-0">
                <a asp-action="Index" asp-controller="Home">
                    <h1 class="text-primary m-0">
                        <i class="fa fa-utensils me-3"></i>Restoran
                    </h1>
                </a>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0 pe-4">
                    <a asp-action="Index" asp-controller="Home" class="nav-item nav-link @((ViewContext.RouteData.Values["Action"] != null && ViewContext.RouteData.Values["Action"].ToString() == "Index" && ViewContext.RouteData.Values["Controller"] != null && ViewContext.RouteData.Values["Controller"].ToString() == "Home") ? "active" : "")">Home</a>
                    <a asp-action="About" asp-controller="Home" class="nav-item nav-link @(ViewContext.RouteData.Values["Action"] != null && ViewContext.RouteData.Values["Action"].ToString() == "Menu" && ViewContext.RouteData.Values["Controller"] != null && ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active" : "")">About</a>
                    <a asp-action="Menu" asp-controller="Home" class="nav-item nav-link @(ViewContext.RouteData.Values["Action"] != null && ViewContext.RouteData.Values["Action"].ToString() == "About" && ViewContext.RouteData.Values["Controller"] != null && ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active" : "")">Menu</a>
                    @* <a asp-action="Booking" asp-controller="Booking" class="nav-item nav-link @((ViewContext.RouteData.Values["Action"] != null && ViewContext.RouteData.Values["Action"].ToString() == "Booking" && ViewContext.RouteData.Values["Controller"] != null && ViewContext.RouteData.Values["Controller"].ToString() == "Booking") ? "active" : "")">Booking</a> *@

                        @{
                            bool isAuthenticated = User.Identity.IsAuthenticated;
                            string activeClass = (ViewContext.RouteData.Values["Action"] != null && ViewContext.RouteData.Values["Action"].ToString() == "Booking" && ViewContext.RouteData.Values["Controller"] != null && ViewContext.RouteData.Values["Controller"].ToString() == "Booking") ? "active" : "";
                        }

                        @if (!isAuthenticated)
                        {
                            <a href="/Login" class="nav-item nav-link @activeClass">Booking</a>
                        }
                        else
                        {
                            <a asp-action="Booking" asp-controller="Booking" class="nav-item nav-link @activeClass">Booking</a>
                        }
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Index" asp-controller="Admin" class="nav-item nav-link">Admin</a>
                    }
                    <partial name="_LoginPartial"></partial>
                    <form class="d-flex">
                         @if (User.Identity.IsAuthenticated)
                         {
                             <a asp-action="Index" asp-controller="ShoppingCart" class="nav-item nav-link"><i class="bi-cart-fill me-1"></i>Giỏ hàng</a>
                         }
                    </form>
                </div>
            </div>
        </nav>
    </div>
    @* END - HEADER *@

    @* START - BODY *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @* END - BODY *@
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s" />
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Liên Quan</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Reservation</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Liên hệ</h4>
                <p class="mb-2">
                    <i class="fa fa-map-marker-alt me-3"></i>475A Điện Biên Phủ, P.25, Q.Bình Thạnh, TP.HCM
                </p>
                <p class="mb-2">
                    <i class="fa fa-phone-alt me-3"></i>+012 345 67890
                </p>
                <p class="mb-2">
                    <i class="fa fa-envelope me-3"></i>restoran@gmail.com
                </p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Hoạt Động</h4>
                <h5 class="text-light fw-normal">Thứ 2 - Thứ 7</h5>
                <p>09AM - 09PM</p>
                <h5 class="text-light fw-normal">Chủ Nhật</h5>
                <p>10AM - 08PM</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Nhập email của bạn">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Gửi</button>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>